FROM python:3.11-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.6.16 /uv /usr/local/bin/uv

ENV UV_LINK_MODE=copy \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PYTHONUNBUFFERED=1 \
    PRODUCTION_MODE=true

# 1️⃣ copy only the lock + metadata first
WORKDIR /app
ENV PATH="/app/.venv/bin:$PATH"

COPY pyproject.toml uv.lock README.md ./


# 2️⃣ create venv and install deps
RUN uv venv && uv sync --no-cache --locked --link-mode copy

# 3️⃣ now bring in the actual source code
COPY . .

ENV PATH="/app/.venv/bin:$PATH"
# CMD ["uv", "run", "--no-sync", "server"]
CMD ["python", "-m", "beeai_agents.agent"]